project_id = "vonppkdllfzztpibtewy"

[functions.ai-tryon-analysis]
verify_jwt = false

[functions.ai-tryon-image]
verify_jwt = false

[functions.ai-fashion-chat]
verify_jwt = false

[functions.tryon-api]
verify_jwt = false

[functions.expire-api-keys]
verify_jwt = false
